apiVersion: v1
kind: ServiceAccount
metadata:
  name: jgroups-sa
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jgroups-role-binding
subjects:
- kind: ServiceAccount
  name: jgroups-sa
roleRef:
  kind: Role
  name: jgroups-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jgroups-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]